config/routes.rb
OpenContractIntake::Application.routes.draw do
  resources :projects do
    member do
      post :add_stakeholder
      post :add_adversary
    end
  end
  post 'add_stakeholder' => 'projects#add_stakeholder'
  post 'add_adversary' => 'projects#add_adversary'
  root to: 'projects#new'
end

app/models/adversary.rb
class Adversary < ActiveRecord::Base
  has_many :memberships, :as => :member
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :project
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :member, :polymorphic => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :documents
  has_many :memberships
  has_many :stakeholders, :as => :member
  has_many :adversaries, :as => :member
end

app/models/stakeholder.rb
class Stakeholder < ActiveRecord::Base
  has_many :memberships, :as => :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def add_stakeholder
    @stakeholder = Stakeholder.new
    @stakeholder.name = params[:term]
    @stakeholder.save
    respond_to do |format|
      format.js
    end
  end

  def add_adversary
    @adversary = Adversary.new
    @adversary.name = params[:term]
    @adversary.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :spend)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenContractIntake</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :spend %><br />
    <%= f.text_field :spend %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/add_adversary.js.erb
$(document).ready(function() {

  var newOption = '<option value="<%= @adversary.id %>"><%= @adversary.name %></option>';
  $('#project_adversary_id').append(newOption);
  var selectOptions = $("#project_adversary_id option");
  selectOptions.sort(function(a, b) { if (a.text > b.text) { return 1; } else if (a.text < b.text) { return -1; } else { return 0 } });
  $("#project_adversary_id").empty().append(selectOptions).trigger("liszt:updated");
  setTimeout(function(){
    $('#project_adversary_id').val("<%= @adversary.id %>").trigger("liszt:updated");
  }, 200);


});

app/views/projects/add_stakeholder.js.erb
$(document).ready(function() {

  var newOption = '<option value="<%= @stakeholder.id %>"><%= @stakeholder.name %></option>';
  $('#project_stakeholder_id').append(newOption);
  var selectOptions = $("#project_stakeholder_id option");
  selectOptions.sort(function(a, b) { if (a.text > b.text) { return 1; } else if (a.text < b.text) { return -1; } else { return 0 } });
  $("#project_stakeholder_id").empty().append(selectOptions).trigger("liszt:updated");
  setTimeout(function(){
    $('#project_stakeholder_id').val("<%= @stakeholder.id %>").trigger("liszt:updated");
  }, 200);


});

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spend</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.spend %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="span8 offset2">
      <div class="vertical-spacer"></div>
      <p class="lead">New Project</p>
      <div class="vertical-spacer"></div>
      <%= semantic_form_for @project do |f| %>
        <%= f.inputs do %>
          <%= f.input :documents, :as => :file, :input_html => {:multiple => "true"} %>
          <%= f.input :stakeholders, :as => :select, :collection => Stakeholder.all.to_a, :label => "Stakeholder Names", :input_html => {"data-placeholder" => "Choose...", :multiple => true} %>
          <%= f.input :adversaries, :as => :select, :collection => Adversary.all.to_a, :label => "Adverse Party Names", :input_html => {"data-placeholder" => "Choose...", :multiple => true} %>
          <%= f.input :spend, :input_html => {:style => "width:220px;"} %>
        <% end %>

        <%= f.actions do %>
          <%= f.action :submit, :as => :input, :button_html => {:class => "btn btn-primary"} %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Spend:</strong>
  <%= @project.spend %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>